default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: krushna
  password: admin2022
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: ecomm_database

test:
  <<: *default
  database: ecomm_database

production:
  <<: *default
  database: ecomm_database
